name: pokifairy
description: "Pocket fairy companion app scaffold with Riverpod, GoRouter, and localized UI."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^16.2.2
  flutter_riverpod: ^3.0.0
  shared_preferences: ^2.5.3
  lottie: ^3.3.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flame: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: assets/images/PockiFairy.png
  min_sdk_android: 21
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/images/PockiFairy.png
    background_color: "#BDE0FE"
    theme_color: "#BDE0FE"
  windows:
    generate: true
    image_path: assets/images/PockiFairy.png
  macos:
    generate: true
    image_path: assets/images/PockiFairy.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/lottie/placeholder.json
    - assets/images/PockiFairy.png
    - assets/icons/pokifairy.png
    - assets/images/character/
    - assets/images/character/talk/
